{% set OAP_VERSION = "1.3.0" %}
package:
  name: oap
  version: {{ OAP_VERSION }}

source:
  path: ../../../thirdparty/arrow/

build:
  build:
  number: 3
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("oap", max_pin="x.x") }}

requirements:
  build:
    - cmake 3.16.*
    - autoconf  # [unix]
    - ninja
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}


  run:
    - libhdfs3
    - gcc_impl_linux-64  7.5.0
    - gcc_linux-64       7.5.0
    - gxx_impl_linux-64  7.5.0
    - gxx_linux-64       7.5.0
    - curl               7.78



about:
  summary: Optimized Analytics Packages for Spark is a project to optimize Spark by providing optimized implmentation of packages in various aspects including cache, shuffle, and so on.
  home: https://oap-project.github.io/
  license:  Apache License 2.0
  license_file:
    - LICENSE.txt
    - TPP.txt
  description:
    '<strong>LEGAL NOTICE: Use of this software package is subject to the software license agreement (as set forth above, in
      the license section of the installed Conda package and/or the README file) and all notices, disclaimers or license terms
      for third party or open source software included in or with the software.</strong>
      <br/><br/>
      EULA: <a href="https://github.com/oap-project/oap-tools/blob/master/LICENSE.txt" target="_blank">Apache License 2.0</a><br/>
      Third Party Programs: https://github.com/oap-project/oap-tools/blob/master/TPP.txt
      <br/><br/>'
  dev_url: https://github.com/oap-project
  doc_url: https://oap-project.github.io/

