apiVersion: v1
kind: Pod
metadata:
  name: spark-client
  labels:
    app: spark-client
spec:
  serviceAccountName: spark
  containers:
  - name: spark-client-container
    imagePullPolicy: IfNotPresent
    image: $CONTAINER_IMAGE
    args: ["/opt/home/entrypoint-nop.sh"]
    volumeMounts:
      - name: spark-conf-volume 
        mountPath: /opt/home/conf
    envFrom:
    - configMapRef:
        name: spark-client-configmap
  volumes:
    - name: spark-conf-volume 
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: spark-client-conf