apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-thrift-server-configmap
data:
  kubernetes_svc_address: "$K8S_SVC_ADDRESS"
  spark_kubernetes_driver_pod_name: "spark-thrift-server"
  spark_driver_host: "spark-thrift-server-headless-service.default.svc.cluster.local"
  spark_driver_port: "1888"
  spark_kubernetes_container_image: "$CONTAINER_IMAGE"