apiVersion: v1
kind: Service
metadata:
  name: spark-thrift-server-loadbalancer-service
spec:
  type: LoadBalancer
  ports:
  - port: 30000
    targetPort: 10000
  selector:
    app: spark-thrift-server